### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by emanlodovice** [emanlodovice/ana#11]

**Comment by munadikieh** [comment]
Hi @arnellebalane 
I,m Munadi Kiehl, Graphic Designer, I like to help the open source project.

**Comment by aldnav** [comment]
Wow @munadikieh yes! Your help is highly appreciated! 🚀

**Comment by munadikieh** [comment]
Thanks @aldnav :)
Can you describe the logo design for this project?

**Comment by arnellebalane** [comment]
@munadikieh Thank you for your interest in this project! 💯 

This project, **ana**, is basically an analytics tool, so we're expecting to be showing a lot of graphs to the user. The logo design will most likely dictate the design direction of these other components. We don't have anything concrete in mind yet on how the logo looks like, but something simple but unique would be good.

**Comment by munadikieh** [comment]
Thanks for your reply.
Could you pelase clarify some information.
1. Where do you plan to use the logo?
2. Should it include any text or specific object?
3. Colorful or any other wishes ?
4. Do you have messenger like Discord? this is my ID Discord : munadikiehl#0187

**Comment by munadikieh** [comment]
Hi @aldnav @arnellebalane 
Sorry, I'm late in replying to your message, because I'm still working on another project. I tried a minimalist logo design. If there is any revision, please tell to me.
![asset 3](https://user-images.githubusercontent.com/41304326/52991870-1a48ad80-3441-11e9-9265-a2306092179c.png)

**Comment by emanlodovice** [comment]
@munadikieh nice. I like the black text with white background. Really nice. Good work.

**Comment by arnellebalane** [comment]
@munadikieh These look really cool! I like this, well done! 💯

I would like to request the following:
1. A horizontal layout of the logo (i.e. the **Analytics** word to the right of the logo)
2. A tiny square version of the logo, which will be used for the site favicon

Thanks! Again, really good job on this! 🎉

**Comment by arnellebalane** [comment]
@emanlodovice @aldnav Someone should update this repo's readme to display the logo created by @munadikieh 😄

**Comment by aldnav** [comment]
@munadikieh Great work! I like it very much.

@arnellebalane @emanlodovice I'll update it once the logo is finalized. Just give me the go signal.

**Comment by munadikieh** [comment]
Thanks everyone 😉
I'll update the logo asap.

**Comment by munadikieh** [comment]
Hi everyone :)
I have another idea, please give me your opinion.
![aartboard 2](https://user-images.githubusercontent.com/41304326/53148114-3c2a6780-35dc-11e9-8033-dc11af1c8157.png)

**Comment by emanlodovice** [comment]
@munadikieh  my god these are all amazing. I like 6 the most, very creative with the combination of bar graph and line graph. 🔥

**Comment by aldnav** [comment]
@munadikieh are you for real? Wow, these designs we could not afford if not for you. ❤️ I like **(5)** because it's minimal and elegant. Yet again, all of these designs are superb! Thank you. _(I'd like to add you on LinkedIn if that's okay?)_

**Comment by munadikieh** [comment]
Thanks for your kind words guys, Of course you can do that, I'm so glad to hear add me on LinkedIn. 
Hopefully ANA becomes a good project and useful. Anyway, which one the logo to use it?, or if there is a revision, I am ready for it.

**Comment by emanlodovice** [comment]
@munadikieh for me I am going with 6. If you can give us a png or svg of that that would be great 💯 🔥

**Comment by munadikieh** [comment]
Hello everyone 
This is the Original File of ANAlytics : 
https://drive.google.com/drive/folders/1pLWFmdtGoS9y0lSzvUL0bkNwhUoX_aUc?usp=sharing
